name: Test GIS models

on:
  push:
    paths:
      - 'gis/**/*.py'  # If a gis model is modified
      - 'test_gis_examples.py'  # If the gis test script is modified
      - '.github/workflows/test_gis_examples.yml'  # If this workflow is modified
  pull_request:
    paths:
      - 'gis/**/*.py'
      - 'test_gis_examples.py'
      - '.github/workflows/test_gis_examples.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Monday at 6:00 UTC

jobs:
  build-08-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install "mesa-geo<0.9"
        pip install .[test_gis]
    - name: Test with pytest
      run: pytest -rA -Werror test_gis_examples.py

  build-08-git:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        pip install -U git+https://github.com/projectmesa/mesa-geo@0.8.x-maintenance#egg=mesa-geo
        pip install .[test_gis]
    - name: Test with pytest
      run: pytest -rA -Werror test_gis_examples.py
